---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: sgpsgpsgp/rails-tutorial-sample-app
        env:
          - name: RAILS_ENV
            value: development
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rails
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  selector:
    app: rails
